### PR TITLE
Example showing 3D stencil calculations.

### LINKED ISSUE #12: Best way to GPUify nested loops over multi-dimensional arrays?
I'm hoping to use GPUifyLoops.jl to rewrite the time stepping for [Oceananigans.jl](https://github.com/ali-ramadhan/Oceananigans.jl).

I'm just starting very small (basically building off the simple example with the `A[i] = 2*A[i]` kernel) but since my model works with 3D arrays I was wondering about the best way to iterate over arrays with sizes like 128×128×64. Here is what I have so far

```julia
using BenchmarkTools
using CUDAnative, CuArrays
using GPUifyLoops

@inline incmod1(a, n) = a == n ? 1 : a+1  # Wrap around indexing for i+1.
δx(f, Nx, i, j, k) = f[incmod1(i, Nx), j, k] - f[i, j, k]  # x-difference operator

function time_stepping_kernel(::Val{Dev}, f, δxf) where Dev
    @setup Dev
    
    Nx, Ny, Nz = size(f)
    @loop for i in (1:Nx; threadIdx().x)
        for k in 1:Nz, j in 1:Ny
            δxf[i, j, k] = δx(f, Nx, i, j, k)
        end
    end
    
    @synchronize
end

time_step!(A::Array, B::Array) = time_stepping_kernel(Val(:CPU), A, B)

function time_step!(A::CuArray, B::CuArray)
    @cuda threads=512 time_stepping_kernel(Val(:GPU), A, B)
end
```
but then this kernel is quite slow
```julia
julia> Nx, Ny, Nz = 128, 128, 64
julia> xc, yc = rand(Nx, Ny, Nz), rand(Nx, Ny, Nz);
julia> xg, yg = cu(rand(Nx, Ny, Nz)), cu(rand(Nx, Ny, Nz));

julia> @benchmark time_step!($xc, $yc)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     5.830 ms (0.00% GC)
  median time:      5.843 ms (0.00% GC)
  mean time:        5.874 ms (0.00% GC)
  maximum time:     7.908 ms (0.00% GC)
  --------------
  samples:          851
  evals/sample:     1

julia> @benchmark time_step!($xg, $yg)
BenchmarkTools.Trial: 
  memory estimate:  288 bytes
  allocs estimate:  7
  --------------
  minimum time:     3.728 μs (0.00% GC)
  median time:      4.657 ms (0.00% GC)
  mean time:        4.344 ms (0.00% GC)
  maximum time:     4.663 ms (0.00% GC)
  --------------
  samples:          144
  evals/sample:     8
```
while I was hoping for a ~10x speed up compared to single-core CPU performance (see [this thread on Julia Discourse](https://discourse.julialang.org/t/writing-fast-stencil-computation-kernels-that-work-on-both-cpus-and-gpus/20200/2?u=polarizedpoutine)). I'm guessing it's slow because I'm only using a single block maybe? Is there a way to speed up `time_stepping_kernel` with GPUifyLoops.jl?

I also have a few questions:
1. Is it possible to use up as many threads as possible? I think broadcasting over CuArrays does this?
2. I should probably read up again on CUDA threads and blocks but is it possible to use `blockId`, `blockDim`, and `gridDim` with GPUifyLoops.jl?
3. I get a `CUDA error: too many resources requested for launch (code #701, ERROR_LAUNCH_OUT_OF_RESOURCES)` if I ask for too many threads (e.g. 1024). Googling around suggests that not enough registers are available. I assume I should probably be using blocks as well as threads to avoid jamming too many threads per block?

Thanks so much!

EDIT: Forgot to mention that this is with Julia 1.1, CUDA 9.2, and a Tesla V100.

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Example might be useful to others. I get a speedup of ~85x with this small kernel (compared to single CPU core, so it's not really a fair comparison) so I think I did it right but please fix/amend as necessary.

Resolves #12

### CODE REVIEW

**Comment by vchuravy** [comment]
Hm I wonder why the tests are not being run here.

**Comment by vchuravy** [comment]
Please rebase on master and take a look at https://github.com/vchuravy/GPUifyLoops.jl/blob/master/examples/simple.jl the examples are both tested on CPU and GPU only environments and as such the GPU part needs to be conditional.

**Comment by vchuravy** [comment]
bors try

**Comment by ali-ramadhan** [comment]
Example should run on both CPU and GPU now. Will only run on the GPU if CuArrays is found.

Git noob here and first time rebasing. Lemme know if I screwed up (looks like I merged some stuff?) and I can nuke this pull request and open a clean one.

**Comment by vchuravy** [comment]
Yeah do a:
```
git fetch
git rebase -i origin/master
```

Drop all the commits that are unnecessary.

**Comment by ali-ramadhan** [comment]
I'll learn to rebase another day.

**Pull request closed without merging**
