### PR TITLE
fix inferrability of cpu shmem arrays

### LINKED ISSUE #83: `@shmem` with integer results in `Any`
Got bit by this one today. If the size of an `@shmem` is an integer (as opposed to a `Tuple`) on the CPU then `Any` results.

```julia
using GPUifyLoops

# Integer for size of shmem
function ker1!(::Val{Nq}, y, x) where Nq
  s_x = @shmem eltype(x) Nq # <<<< HERE
  @inbounds @loop for i in (1:Nq; threadIdx().x)
    s_x[i] = x[i]
  end
  nothing
end

# tuple for size of shmem
function ker2!(::Val{Nq}, y, x) where Nq
  s_x = @shmem eltype(x) (Nq, ) # <<<< HERE
  @inbounds @loop for i in (1:Nq; threadIdx().x)
    s_x[i] = x[i]
  end
  nothing
end

function main(Nq = 10)
  x = rand(Nq)
  y = similar(x)

  @time @launch CPU() threads=(Nq,) ker1!(Val(Nq), y, x)
  @time @launch CPU() threads=(Nq,) ker2!(Val(Nq), y, x)
end
```

```
julia> main()
  0.000087 seconds (57 allocations: 2.469 KiB)
  0.000023 seconds (4 allocations: 96 bytes)
```

`@code_warntype` reveals that `s_x` is an `Any` in `ker1!`

### PR DESCRIPTION
**Pull request by vchuravy**
fixes #83

### CODE REVIEW

**Comment by vchuravy** [comment]
@jkozdon Is this also a issue on GPU code?

**Comment by jkozdon** [comment]
I didn't see a performance degradation on the GPU, so I assume not. But will check....

**Comment by jkozdon** [comment]
There does not seem to be any problems in cuda.

**Comment by jkozdon** [comment]
If there were, would the gpu code have even run?

**Pull request merged**
