### PR TITLE
switch from Val{:CPU} to proper types

### PR DESCRIPTION
**Pull request by vchuravy**
Prompted by https://github.com/climate-machine/Oceananigans.jl/pull/103#issuecomment-469082916

CC: @glwagner @ali-ramadhan 

bors try

### CODE REVIEW

**Comment by glwagner** [comment]
Fun stuff!

**Comment by jkozdon** [comment]
In https://github.com/climate-machine/Oceananigans.jl/pull/103#issuecomment-469085721 it's mentioned

> That might make the code slightly faster too, right?

Is that true? If so why?

**Comment by glwagner** [comment]
I might be completely wrong! But it seems there’s some notion that dispatching on a value (like :GPU) rather than a type sucks up some time:

https://discourse.julialang.org/t/dispatch-on-argument-values-rather-than-just-types/7974/1

I course, I am quite low on the ranked list of “people who understand the Julia compiler”. Constant propagation is mysterious and awe-inspiring to me. 

Also possibly irrelevant if kernel cost dwarfs the 100 ns value-checking time.

**Comment by vchuravy** [comment]
Meh, not really any difference for how we used it. We weren't relying on constant propagation. But I do agree that that the type based system is nicer in the end.

**Comment by vchuravy** [comment]
bors try

**Pull request merged**
