### PR TITLE
Add cassette based contextualize

### PR DESCRIPTION
**Pull request by vchuravy**
Simple cassette based methods substitution

#### TODO:
- [x] Don't inline `@noinline`

### CODE REVIEW

**Comment by vchuravy** [comment]
Just stumbled across this snippet:

```
force_noinline = _any(@nospecialize(x) -> isexpr(x, :meta) && x.args[1] == :noinline, ir.meta)
```

**Comment by vchuravy** [comment]
In https://github.com/JuliaGPU/CUDAnative.jl/pull/334 we figured out most of the issues, but there are still a few drawbacks that make me hesitant from adding it here.
The biggest one is that the kernel functions will no longer see redefinitions. https://github.com/JuliaGPU/CUDAnative.jl/pull/334#issuecomment-466523983 works around this,
but it is a major bodge. 

@lcw I remember we discussed this in the context of user-defined functions that are passed to kernels. Do we have a concrete example of that yet?

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
@lcw this should now be in a state for you to look at.
The broken test works on the REPL but fails in the test file :/

**Comment by lcw** [comment]
Cool!  I'll check it out.

**Comment by lcw** [comment]
@vchuravy, I got the following code to work! 

```julia
using GPUifyLoops
using Random
using Test

f1(x) = sin(x)
f(x) = 1 + f1(x)

kernel(A::Array) = kernel(CPU(), A, f)
function kernel(::Dev, A, h) where Dev
    @setup Dev
    @loop for i in (1:size(A,1);
                    threadIdx().x)
        A[i] = h(A[i])
    end
end

rnd = MersenneTwister(0)
data = rand(rnd, Float32, 12)

@static if Base.find_package("CuArrays") !== nothing

    using CuArrays
    using CUDAnative

    @eval function kernel(A::CuArray)
        g(x) = GPUifyLoops.contextualize(f)(x)
        @cuda threads=length(A) kernel(CUDA(), A, g)
    end

    d_data = CuArray(data)

    desired = f.(data)

    kernel(d_data)

    @test desired ≈ d_data

    kernel(data)

    @test desired ≈ data
end
```

 I have a couple of questions before I submit something like this as a test.

First, CUDAnative gives a warning (see below) because it thinks we are still calling `sin` from base.  Is there a way to work around this?

```
julia> include("simple.jl")
┌ Warning: calls to Base intrinsics might be GPU incompatible
│   exception =
│    You called sin(x::T) where T<:Union{Float32, Float64} in Base.Math at special/trig.jl:30, maybe you intended to call sin(x::Float32) in CUDAnative at /home/lwilcox/.julia/packages/CUDAnative/VViVb/src/device/libdevice.jl:13 instead?
│    Stacktrace:
│     [1] sin at special/trig.jl:30
│     [2] #24 at /home/lwilcox/research/code/julia-local-packages/GPUifyLoops/src/context.jl:90
│     [3] kernel at /home/lwilcox/research/code/gpuknls/simple.jl:10
└ @ CUDAnative ~/.julia/packages/CUDAnative/VViVb/src/compiler/irgen.jl:68
┌ Warning: calls to Base intrinsics might be GPU incompatible
│   exception =
│    You called sin(x::T) where T<:Union{Float32, Float64} in Base.Math at special/trig.jl:30, maybe you intended to call sin(x::Float32) in CUDAnative at /home/lwilcox/.julia/packages/CUDAnative/VViVb/src/device/libdevice.jl:13 instead?
│    Stacktrace:
│     [1] sin at special/trig.jl:30
│     [2] #24 at /home/lwilcox/research/code/julia-local-packages/GPUifyLoops/src/context.jl:90
│     [3] kernel at /home/lwilcox/research/code/gpuknls/simple.jl:10
└ @ CUDAnative ~/.julia/packages/CUDAnative/VViVb/src/compiler/irgen.jl:68
Test Passed
```

Second, I had to pass in the contextualized function as an argument to the kernel.  Is this the way it is designed to work?

I needed to do this because once I call `g(x) = GPUifyLoops.contextualize(f)(x)` I can only call `g` in a CUDA kernel.  It doesn't work on the host anymore.  Is this expected?

**Comment by vchuravy** [comment]
> Second, I had to pass in the contextualized function as an argument to the kernel. Is this the way it is designed to work?

Yes! Right now that is the only way to do that until we have https://github.com/vchuravy/GPUifyLoops.jl/pull/20, and then we can contextualize entire kernels.

> First, CUDAnative gives a warning (see below) because it thinks we are still calling sin from base. Is there a way to work around this?

Weird that should no longer be the case...

**Comment by jkozdon** [comment]
Great! Thanks for getting this working.

**Comment by lcw** [comment]
bors try

**Comment by lcw** [comment]
bors try

**Comment by lcw** [comment]
@vchuravy Do you think contextualize should take in the execution type?  So it would become something like
`g(x) = GPUifyLoops.contextualize(CUDA(),f)(x)`.  This would allow for AMD or other backends.

**Comment by lcw** [comment]
bors try

**Comment by lcw** [comment]
bors try

**Comment by lcw** [comment]
bors try

**Pull request merged**
